[server]
headless = true
address = "0.0.0.0"
# Streamlit Cloud expects default 8501
port = 8501
enableCORS = false
enableXsrfProtection = true

[theme]
base = "light"
primaryColor = "#4F46E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6FA"
textColor = "#111827"

[logger]
level = "info"
